name: documentation

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Test Build
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Add key to allow access to repository seb
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW\nQyNTUxOQAAACDRA6+BifuQhMAiZkZnvg6lkUPnmWfS9BoALl/7vHiNrAAAAKBhcsBEYXLA\nRAAAAAtzc2gtZWQyNTUxOQAAACDRA6+BifuQhMAiZkZnvg6lkUPnmWfS9BoALl/7vHiNrA\nAAAECdCLum+o32mfhsewf1rSvK9/sQ9hmf0mT07myf0+P3edEDr4GJ+5CEwCJmRme+DqWR\nQ+eZZ9L0GgAuX/u8eI2sAAAAFnNlYmFzdGllbi5iaW5kYUBjLXMuZnIBAgMEBQYH\n-----END OPENSSH PRIVATE KEY-----" > ~/.ssh/id_ed25519
          cat ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_ed25519
          EOT
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git          
          DEPLOYMENT_BRANCH: gh-pages
        run: |
          git config --global user.email "actions@gihub.com"
          git config --global user.name "gh-actions"
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npx docusaurus deploy
